name: Build release APK
description: Builds the release apk and signs it

runs:
  using: "composite"
  steps:
    - name: Retrieve the keystore secret and decode it to a file
      env:
        KEYSTORE_B64: ${{ secrets.KEYSTOREB64 }}
      run: |
        echo $KEYSTORE_B64 | base64 --decode > app/keystore.jks
    - name: set up java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Setup gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Create release app with gradle
      env:
        STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
      run: ./gradlew assembleRelease