name: Android CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Retrieve the keystore secret and decode it to a file
      env:
        KEYSTORE_B64: ${{ secrets.KEYSTOREB64 }}
      run: |
        echo $KEYSTORE_B64 | base64 --decode > app/keystore.jks
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Build with Gradle
      uses: gradle/actions@v3.3.2
    - name: Create release app with gradle
      env:
        STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
      run: ./gradlew assembleRelease
    - name: Upload release apk
      uses: actions/upload-artifact@v4
      with:
        name: apk_release
        path: app/build/outputs/apk/release/app-release.apk
