name: Create a nightly release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Create release apk
      uses: ./.github/actions/build-release-apk
    - name: Rename release apk
      run: mv app/build/outputs/apk/release/app-release.apk FitnessCalendar-Nightly.apk
    - name: Upload release apk
      uses: actions/upload-artifact@v4
      with:
        name: FitnessCalendar-Nightly
        path: FitnessCalendar-Nightly.apk

  create_prerelease:
    runs-on: ubuntu-latest
    needs: [ build ]
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@master
      - run: mkdir release_binaries
      - name: Download release binaries
        uses: actions/download-artifact@master
        with:
          name: FitnessCalendar-Nightly
          path: release_binaries
      - name: Delete previous release
        env: 
          GH_TOKEN: ${{ github.token }}
        run: gh release delete "Nightly" --cleanup-tag --yes
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          commit: "master"
          tag: "Nightly"
          artifacts: "release_binaries/*"
          allowUpdates: true
          makeLatest: true
          omitBody: true
          prerelease: true
