name: Create a new release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Retrieve the keystore secret and decode it to a file
        env:
          KEYSTORE_B64: ${{ secrets.KEYSTOREB64 }}
        run: |
          echo $KEYSTORE_B64 | base64 --decode > app/keystore.jks
      - name: set up java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Create release app with gradle
        env:
          STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
        run: ./gradlew assembleRelease
      - name: Rename release apk
        run: mv app/build/outputs/apk/release/app-release.apk FitnessCalendar-${{ github.ref_name }}.apk
      - name: Upload release apk
        uses: actions/upload-artifact@v4
        with:
          name: FitnessCalendar-${{ github.ref_name }}
          path: FitnessCalendar-${{ github.ref_name }}.apk

  create_release:
    runs-on: ubuntu-latest
    needs: [ build ]
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@master
      - run: mkdir release_binaries
      - name: Download release binaries
        uses: actions/download-artifact@master
        with:
          name: FitnessCalendar-${{ github.ref_name }}
          path: release_binaries
      - name: Create Changelog file
        run: source tools/_functions.sh; getChangelog $versionCode > release_notes.md
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release_binaries/*"
          bodyFile: "release_notes.md"
