name: Create a new release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Create release apk
        uses: ./.github/actions/build-release-apk
      - name: Rename release apk
        run: mv app/build/outputs/apk/release/app-release.apk FitnessCalendar-${{ github.ref_name }}.apk
      - name: Upload release apk
        uses: actions/upload-artifact@v4
        with:
          name: FitnessCalendar-${{ github.ref_name }}
          path: FitnessCalendar-${{ github.ref_name }}.apk

  create_release:
    runs-on: ubuntu-latest
    needs: [ build ]
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@master
      - run: mkdir release_binaries
      - name: Download release binaries
        uses: actions/download-artifact@master
        with:
          name: FitnessCalendar-${{ github.ref_name }}
          path: release_binaries
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release_binaries/*"
          omitBody: true
